### ISSUE TITLE
Passing width/height argument fails

### ISSUE THREAD

**Issue by bzhb** [Ksengine/Zenity#1]
`zenity.show(zenity.info,text="Stuff",width=800,height=600)`

Fails because the module convert the arguments as string to `--width="800"` instead of zenity expected `--width=800`

This issue should exist with any zenity supported parameter that is not of type string

**Comment by Ksengine** [comment]
I had tested it on my console.

---
```python
zenity --info --width=800
```
**works**

---
```python
zenity --info --width="800"
```
**works**

---

**Comment by Ksengine** [comment]
Error is in python code. i fixed it. use code in github repo.

**Comment by Ksengine** [comment]
thank you @bzhb. you showed a bug.

**Comment by Ksengine** [comment]
**Use https://github.com/QuantumGUI/SmokeMSG instead of this library. I am the creator of it.**
if you want a linux only solution, you can use https://github.com/QuantumGUI/SmokeMSG/blob/main/smokemsg/zenity.py file.

**Comment by bzhb** [comment]
Ok, thanks for the fast fix and the info about SmokeMSG

**Comment by bcbernardo** [comment]
I believe this bug persists as it was first described, at least in `master` branch (and hence in PyPI). The proposed patch ( #2 ) seems to contain two commits that cancel each other.

Also, SmokeMSG links above are broken 😕
